### ISSUE TITLE
和vue.js结合用的问题

### ISSUE THREAD

**Issue by ChangeZhang** [fa-ge/Scrollload#1]
![image](https://cloud.githubusercontent.com/assets/6948367/22008399/dc3a9966-dcb5-11e6-9df8-eec8d3f20154.png)
![test](https://cloud.githubusercontent.com/assets/6948367/22008435/2f60f0ae-dcb6-11e6-9197-32dee972ce52.gif)

**Comment by ChangeZhang** [comment]
求大神看一下

**Comment by fa-ge** [comment]
我太懂vue，我能看出来的问题是当你调用一次getProductItem方法的时候你就会去new Scrollload。而文档上的用法是一个列表只需要new 一次就可以了。所以new Scrollload的最佳时机应该是当组件插入到文档的时候去做。而且这里不要去remove插件的scrollload-bottom这个dom，如果你想改变这个dom中的显示。可以设置setOptions中的notaDataHtml,loadingHtml等。

**Comment by ChangeZhang** [comment]
感谢，解决了
