### ISSUE TITLE
在react项目中使用时会提示container must be a HTMLElement instance！

### ISSUE THREAD

**Issue by frmachao** [fa-ge/Scrollload#13]
项目环境 react15.4
使用方式：
 import Scrollload from 'Scrollload'，
在componentDidMount之后 将实例化Scrollload的代码插入到render之中
出现问题：在实例化Scrollload 时 控制台提示container must be a HTMLElement instance！

**Comment by fa-ge** [comment]
container你传的是啥？你拿到的得是dom，而不是vdom

**Comment by frmachao** [comment]
1. 感谢提醒Vdom的问题，我使用$(ReactDOM.findDOMNode(this.refs.scrollload-container))获取到了真实DOM,解决了container must be a HTMLElement instance！的问题
2. 继续使用时遇到提示container is not defined
使用方式：在componentDidMount之后 将实例化Scrollload的代码插入到render之中
