### ISSUE TITLE
vue中怎样使用呢

### ISSUE THREAD

**Issue by sky-gg** [fa-ge/Scrollload#17]
在vue里能直接操作dom么？

**Comment by logan70** [comment]
Vue中只会更简单，初始化的其他项差不多，拉取接口数据后更新数据即可，而不需要操作Dom，但是需要注意的是：`sl.unLock()`的调用应该放在`this.$nextTick(() => {...// 放在这里})`，因为要等Dom更新才解锁，否则可能多次重复加载
