### ISSUE TITLE
重新加载列表数据

### ISSUE THREAD

**Issue by lemon-go** [fa-ge/Scrollload#2]
现我的需求是列表数据已加载（但**未全部加载完**），此时我想重新加载列表，即重置从第一页重新加载。我看文档给的一个方法是

> refreshData(): 当你调用完noData方法后，如果你想刷新当前的数据重新加载就要调用这个方法

无论是从解释上看，还是从我的调用结果看，都无法实现从效果，请问有提供这样的函数吗？

**Comment by fa-ge** [comment]
你这么一说我倒是被你提醒了。。现在调用refreshData之前必须先清空dom。可以参考列子https://github.com/fa-ge/Scrollload/blob/master/src/feature-demos/demo5/index.js
现在我在想确实可以连清空dom的操作都由框架来完成会不会更好一点。

**Comment by lemon-go** [comment]
多谢，已解决。
我觉得有框架提供此接口是很有必要的，因为在修改查询条件后重新从第一页开始请求展示数据这种需求还是比较常见的【供参考】。 @fa-ge
