### ISSUE TITLE
ios下局部滚动的问题

### ISSUE THREAD

**Issue by wjj5728** [fa-ge/Scrollload#4]
头部和尾部 都是有fixed 的div  然后中间一个大的div  大的div里面最上面有3个tab栏  然后下面的内容content做滚动，在ios下面  有时候content做滚动，突然就编程了  content和3个tab栏一起滚动 ，请问这是局部滚动的坑吗

**Comment by fa-ge** [comment]
有没有在线demo。感觉应该是的。
